apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: publicsubs
  namespace: subscription
  labels:
    app: publicsubs
spec:
  selector:
    matchLabels:
      app: publicsubs
  replicas: 1
  template:
    metadata:
      labels:
        app: publicsubs
    spec:
      containers:
        - name: publicsubs
          image: publicsubs:latest
          ports:
            - containerPort: 8000